
package com.sahand.issuer.services.missingTransaction;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MissingTransaction", targetNamespace = "http://service.loyalty.authorizer.sahand.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MissingTransactionService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.issuer.services.missingTransaction.AuthorizerResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "confirmManualMissingTransaction", targetNamespace = "http://service.loyalty.authorizer.sahand.com/", className = "com.sahand.issuer.services.missingTransaction.ConfirmManualMissingTransaction")
    @ResponseWrapper(localName = "confirmManualMissingTransactionResponse", targetNamespace = "http://service.loyalty.authorizer.sahand.com/", className = "com.sahand.issuer.services.missingTransaction.ConfirmManualMissingTransactionResponse")
    public AuthorizerResponse confirmManualMissingTransaction(
        @WebParam(name = "arg0", targetNamespace = "")
        AuthorizerRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.issuer.services.missingTransaction.AuthorizerResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProgramRefrences", targetNamespace = "http://service.loyalty.authorizer.sahand.com/", className = "com.sahand.issuer.services.missingTransaction.GetProgramRefrences")
    @ResponseWrapper(localName = "getProgramRefrencesResponse", targetNamespace = "http://service.loyalty.authorizer.sahand.com/", className = "com.sahand.issuer.services.missingTransaction.GetProgramRefrencesResponse")
    public AuthorizerResponse getProgramRefrences(
        @WebParam(name = "arg0", targetNamespace = "")
        AuthorizerRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.issuer.services.missingTransaction.AuthorizerResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerManualMissingTransaction", targetNamespace = "http://service.loyalty.authorizer.sahand.com/", className = "com.sahand.issuer.services.missingTransaction.RegisterManualMissingTransaction")
    @ResponseWrapper(localName = "registerManualMissingTransactionResponse", targetNamespace = "http://service.loyalty.authorizer.sahand.com/", className = "com.sahand.issuer.services.missingTransaction.RegisterManualMissingTransactionResponse")
    public AuthorizerResponse registerManualMissingTransaction(
        @WebParam(name = "arg0", targetNamespace = "")
        AuthorizerRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.issuer.services.missingTransaction.AuthorizerResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerOfflineMissingTransaction", targetNamespace = "http://service.loyalty.authorizer.sahand.com/", className = "com.sahand.issuer.services.missingTransaction.RegisterOfflineMissingTransaction")
    @ResponseWrapper(localName = "registerOfflineMissingTransactionResponse", targetNamespace = "http://service.loyalty.authorizer.sahand.com/", className = "com.sahand.issuer.services.missingTransaction.RegisterOfflineMissingTransactionResponse")
    public AuthorizerResponse registerOfflineMissingTransaction(
        @WebParam(name = "arg0", targetNamespace = "")
        AuthorizerRequest arg0);

}
